# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(451, 225)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 451, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(170, 140, 271, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 54, 21))
        self.label_2.setObjectName("label_2")
        self.tickEdit = QtWidgets.QLineEdit(self.tab)
        self.tickEdit.setGeometry(QtCore.QRect(100, 60, 71, 20))
        self.tickEdit.setObjectName("tickEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(180, 60, 81, 21))
        self.label_3.setObjectName("label_3")
        self.newFileNameEdit = QtWidgets.QLineEdit(self.tab)
        self.newFileNameEdit.setGeometry(QtCore.QRect(270, 60, 121, 20))
        self.newFileNameEdit.setObjectName("newFileNameEdit")
        self.ExecuteBtn = QtWidgets.QPushButton(self.tab)
        self.ExecuteBtn.setGeometry(QtCore.QRect(314, 100, 81, 23))
        self.ExecuteBtn.setObjectName("ExecuteBtn")
        self.showLabel = QtWidgets.QLabel(self.tab)
        self.showLabel.setGeometry(QtCore.QRect(40, 140, 121, 21))
        self.showLabel.setObjectName("showLabel")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(40, 20, 351, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pathEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathEdit.sizePolicy().hasHeightForWidth())
        self.pathEdit.setSizePolicy(sizePolicy)
        self.pathEdit.setObjectName("pathEdit")
        self.horizontalLayout.addWidget(self.pathEdit)
        self.openFileBtn = QtWidgets.QPushButton(self.widget)
        self.openFileBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFileBtn.sizePolicy().hasHeightForWidth())
        self.openFileBtn.setSizePolicy(sizePolicy)
        self.openFileBtn.setMinimumSize(QtCore.QSize(21, 23))
        self.openFileBtn.setObjectName("openFileBtn")
        self.horizontalLayout.addWidget(self.openFileBtn)
        self.horizontalLayout.setStretch(1, 12)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "工具箱"))
        self.label_2.setText(_translate("Form", "人数差值："))
        self.label_3.setText(_translate("Form", "生成后文件名："))
        self.newFileNameEdit.setText(_translate("Form", "TheNewExcel"))
        self.ExecuteBtn.setText(_translate("Form", "生成"))
        self.showLabel.setText(_translate("Form", "Thanks for use it!"))
        self.label.setText(_translate("Form", "文件选中："))
        self.openFileBtn.setText(_translate("Form", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "青年大学习中奖人筛选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Building..."))
